### ISSUE TITLE
LibraryManagementDialog: invalid assembly path handling

### ISSUE THREAD

**Issue by tobitege** [dataweb-GmbH/NShape#7]
In the project "**WinFormsUI**" the class "LibraryManagementDialog.cs", method "**GetAssemblyFilePath**()" uses a UriBuilder to return a path to a given assembly object.
However, this fails for any paths containing a hashtag in their name, e.g.:
**C:\projects\c#\NShape\libs**
The UriBuilder uses the # sign as fragment separator, resulting in above example path to become:
**C:\projects\c**

Easy fix in the above method would be to just return assembly.Location as that contains the full path (tested with VS2019).
I can't see why the UriBuilder is used at all there.

**Comment by kholzinger** [comment]
Thanks for your feedback.
I have corrected the issue so it will be fixed with the next release.

The "UriBuilder" class was initially used for LINUX compatibility because it creates paths delimited by '/' instead of '\', regardless of the operating system. But as the UriBuilder has several drawbacks and creates more issues than it solves, we removed it and now do a simple character replacement.
Seems that we overlooked to remove the UriBuilder from this function.

Best regards,
Kurt
